Repository honeycombio/honeycomb-opentelemetry-python, pull requests merged in 2023-05, with the labels that each got.

#134 Don't init HoneycombOptions on import
  src/honeycomb/opentelemetry/distro.py
  src/honeycomb/opentelemetry/sampler.py
Labels: status: oncall

#136 rel: prepare release 0.2.1b0
  CHANGELOG.md
  pyproject.toml
Labels: no-changelog

#137 docs: add releasing step
  RELEASING.md
Labels: type: documentation, no-changelog
