Repository honeycombio/honeycomb-opentelemetry-python, pull requests merged in 2023-04, with the labels that each got.

#114 maint: improve ci time
  examples/hello-world-flask/Dockerfile
  examples/hello-world/Dockerfile
  smoke-tests/docker-compose.yml
Labels: type: maintenance, no-changelog, version: no bump

#120 maint: change experimental badge to active
  OSSMETADATA
Labels: merge at will, no-changelog, version: no bump

#121 maint: update readme status
  README.md
Labels: merge at will, type: maintenance, no-changelog

#122 maint: use squash merge for dependabot auto-merge
  .github/workflows/auto-merge.yml
Labels: type: maintenance, no-changelog, version: no bump

#127 maint: Update OTel packages to 1.17.0/0.38b0
  examples/hello-world-flask/pyproject.toml
  examples/hello-world/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: version: bump patch, type: maintenance

#128 rel: Prepare v0.2.0b0 release
  CHANGELOG.md
  README.md
  pyproject.toml
Labels: type: maintenance
