Repository honeycombio/honeycomb-opentelemetry-python, pull requests merged in 2023-02, with the labels that each got.

#90 rel: prepare 0.1.1a2
  CHANGELOG.md
  pyproject.toml
Labels: type: maintenance, no-changelog, version: no bump

#85 doc: audit of docstrings for dev-friendliness & relevance
  src/honeycomb/opentelemetry/distro.py
  src/honeycomb/opentelemetry/local_exporter.py
  src/honeycomb/opentelemetry/options.py
  src/honeycomb/opentelemetry/sampler.py
  src/honeycomb/opentelemetry/trace.py
  tests/test_distro.py
  tests/test_local_exporter.py
  tests/test_metrics.py
Labels: type: maintenance

#91 maint: smoke test python app
  .circleci/config.yml
  .gitignore
  DEVELOPING.md
  Makefile
  examples/hello-world/Dockerfile
  examples/hello-world/app.py
  examples/hello-world/poetry.lock
  examples/hello-world/pyproject.toml
  smoke-tests/docker-compose.yml
  smoke-tests/smoke-sdk-grpc.bats
  smoke-tests/smoke-sdk-http.bats
  smoke-tests/test_helpers/utilities.bash
Labels: type: maintenance, version: no bump
