Repository honeycombio/honeycomb-opentelemetry-python, pull requests merged in 2023-03, with the labels that each got.

#83 maint: dockerizing flask app
  examples/hello-world-flask/Dockerfile
  examples/hello-world-flask/app.py
  examples/hello-world-flask/poetry.lock
  examples/hello-world-flask/pyproject.toml
  poetry.lock
  pyproject.toml
  smoke-tests/docker-compose.yml
  smoke-tests/smoke-sdk-http.bats
Labels: type: maintenance

#101 maint: Flask smoke tests for http and collector.
  Makefile
  examples/hello-world-flask/app.py
  poetry.lock
  smoke-tests/docker-compose.yml
  smoke-tests/smoke-sdk-http-flask.bats
  smoke-tests/test_helpers/utilities.bash
Labels: type: maintenance

#96 feat: move away from a ParentBased sampling approach.
  src/honeycomb/opentelemetry/sampler.py
  tests/test_sampler.py
Labels: type: bug, version: bump patch

#105 doc: clarify SDK configuration options (command vs function) and final developing.md & readme.md audits
  DEVELOPING.md
  Makefile
  README.md
  examples/README.md
  examples/hello-world-flask/README.md
  examples/hello-world-flask/app.py
  examples/hello-world/README.md
  examples/hello-world/app.py
Labels: type: documentation, version: no bump

#106 rel: v0.1.1a3
  CHANGELOG.md
  pyproject.toml
Labels: no-changelog, version: no bump

#110 maint: add tests for auto instrumentation
  smoke-tests/smoke-sdk-grpc-flask.bats
  smoke-tests/smoke-sdk-http-flask.bats
Labels: type: maintenance, version: no bump

#111 maint: drop poetry locks from example apps
  .gitignore
  examples/hello-world-flask/poetry.lock
  examples/hello-world/poetry.lock
  examples/hello-world/pyproject.toml
Labels: type: maintenance, version: no bump

#112 rel: prep beta release 0.1.2b0
  CHANGELOG.md
  DEVELOPING.md
  README.md
  examples/README.md
  examples/hello-world-flask/README.md
  examples/hello-world/README.md
  pyproject.toml
  src/honeycomb/opentelemetry/local_exporter.py
  src/honeycomb/opentelemetry/sampler.py
  tests/test_metrics.py
Labels: no-changelog

#113 maint: add auto-merge dependabot workflow
  .github/workflows/auto-merge.yml
Labels: type: maintenance, no-changelog, version: no bump
