Repository honeycombio/honeycomb-opentelemetry-python, pull requests merged in 2024-03, with the labels that each got.

#180 feat: support classic ingest keys
  src/honeycomb/opentelemetry/options.py
  tests/test_options.py
  tests/utils.py
Labels: type: enhancement, merge at will, version: bump minor

#182 maint: add labels to release.yml for auto-generated grouping
  .github/release.yml
Labels: merge at will, type: maintenance, no-changelog, version: no bump

#183 maint: Update ubuntu image in workflows to latest
  .circleci/config.yml
Labels: type: maintenance, version: no bump

#184 maint: Permit updates of indirect dependencies
  poetry.lock
  pyproject.toml
Labels: version: bump patch, type: maintenance
